name: CI (Cabal)

on:
  push:
    branches: [master]
    #paths-ignore: ['**.md']
  pull_request:
    branches: [master]
    types: [opened, synchronize]
    #paths-ignore: ['**.md']

jobs:
  build:
    name: Testing with GHC-${{ matrix.ghc }}, on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        cabal: ["3.2"]
        ghc: ["8.2.2", "8.4.4", "8.6.5"] #, "8.8.4", "8.10.2"]
    env:
      CONFIG: "--enable-tests --enable-benchmarks"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-haskell@v1.1.2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - name: Update dependencies
        run: cabal v2-update $CONFIG
      - name: Freeze dependencies
        run: cabal freeze $CONFIG
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/store
            dist-newstyle
          key: cabal-cache-${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}-${{ hashFiles('hindent.cabal') }}
          restore-keys: |
            cabal-cache-${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}-
            cabal-cache-${{ runner.os }}-${{ matrix.ghc }}-
            cabal-cache-${{ runner.os }}-
      - name: Build
        run: cabal v2-build $CONFIG
      - name: Run tests
        run: cabal v2-test $CONFIG
      - name: Run benchmarks
        run: cabal v2-bench $CONFIG
      - name: Generate documentation
        run: cabal v2-haddock $CONFIG
      - name: Generate tarball
        run: cabal v2-sdist
